### ISSUE TITLE
how to encrypt doc/xls/ppt files?

### ISSUE THREAD

**Issue by n0rv1n** [zurmokeeper/officecrypto-tool#17]
Are there any way to encrypt doc/xls/ppt files?

**Comment by zurmokeeper** [comment]
@n0rv1n Temporarily does not support the encryption of doc/xls/ppt files, please ask what scenarios need to be used, if it is really necessary, you can consider adding these features later!

**Comment by Lxxxxxxy** [comment]
[202407251344_理货明细1699708443335589888.xls](https://github.com/user-attachments/files/16371286/202407251344_.1699708443335589888.xls)

**Comment by Lxxxxxxy** [comment]
[Uploading 202407251458_理货明细1699708443335589888.xls…]()

**Comment by Lxxxxxxy** [comment]
[202407251458_理货明细1699708443335589888.xls](https://github.com/user-attachments/files/16371799/202407251458_.1699708443335589888.xls)

**Comment by Mark-SS** [comment]
[libre_123.xls](https://github.com/user-attachments/files/16371813/libre_123.xls)

**Comment by Lxxxxxxy** [comment]
//设置文件名
        String fileName = DateFormatUtils.format(new Date(), "yyyyMMddHHmm") + "_" + sheetName + ".xls";
        //设置输出头
        response.setContentType("application/vnd.ms-excel;charset=UTF-8");
        response.setCharacterEncoding(StandardCharsets.UTF_8.name());
        response.setHeader("Content-Disposition",
                "attachment;filename=" + URLEncoder.encode(fileName, StandardCharsets.UTF_8.name()));
        //输出文件流
        EasyExcelFactory.write(response.getOutputStream(), objectClass)
                //单元格加密
                .registerWriteHandler(new CustomSheetWriteHandler()).registerWriteHandler(new StyleWriteHandler())
                .registerWriteHandler(new LongestMatchColumnWidthStyleStrategy())
            .autoCloseStream(Boolean.FALSE)
                //excel文件加密
                .password("123")
                //设置输出格式
                .excelType(ExcelTypeEnum.XLS)
                //设置sheet名
                .sheet(sheetName)
                //输出数据
                .doWrite(list);
