### ISSUE TITLE
Haven't done or can't do password checking for agile type?

### ISSUE THREAD

**Issue by yanghoxom** [zurmokeeper/officecrypto-tool#20]
I realize we didn't check whether the password is correct or not for einfo.type is "agile"
as I checked in `nolze/msoffcrypto-tool`, I can see it can verify the password for the agile type
Why we don't implement this?

**Comment by zurmokeeper** [comment]
@yanghoxom You're right, Agile did decrypt it without verifying the password first, maybe I forgot, I think so

**Comment by guillenotfound** [comment]
Hey @zurmokeeper any plans to add this check?
