### ISSUE TITLE
blob.read_shift is not a function

### ISSUE THREAD

**Issue by yanghoxom** [zurmokeeper/officecrypto-tool#21]
When I try to open a xls file
it throws an error
```
index.js:143 Uncaught (in promise) TypeError: blob.read_shift is not a function
    at isEncrypted (index.js:143:1)
```

Here is my code (file is value of input file type)
```
const reader = new FileReader();
reader.onload = async e => {
  let data = e.target.result;
  if (isEncrypted(data)) {
  }
};
reader.readAsArrayBuffer(file);
```

this is my file 
[Book1.xls](https://github.com/zurmokeeper/officecrypto-tool/files/14046804/Book1.xls)

**Comment by zurmokeeper** [comment]
@yanghoxom This problem does exist, thank you

**Comment by zurmokeeper** [comment]
@yanghoxom A new version has been released, just upgrade

**Comment by yanghoxom** [comment]
@zurmokeeper 
sorry for late reply
i tried it a few minutes ago and yeah, I can detect the file has password or not
but it crash on decrypt logic
this is my logic
```
const reader = new FileReader();
reader.onload = async e => {
  let data = e.target.result;
  if (isEncrypted(data)) {
    data = await decrypt(data, { password });
  }
};
reader.readAsArrayBuffer(file);
```
this is log
![image](https://github.com/zurmokeeper/officecrypto-tool/assets/10399540/7de723c6-cf26-4718-b5a3-6c04fca5045c)
![image](https://github.com/zurmokeeper/officecrypto-tool/assets/10399540/efe2d916-137d-4fe4-a9b5-3a21187c8f70)

```
TypeError: invalid suite type
    at Object.createDecipheriv (browser.js:56:1)
    at Object.verifyPw [as verifyPassword] (rc4.js:29:1)
    at Object.decrypt (xls97.js:492:1)
    at decrypt (index.js:74:1)
```

**Comment by zurmokeeper** [comment]
@yanghoxom Indeed there is this problem, I have found out that the front-end will have problems reading xls,doc,ppt, it should be caused by the front-end encryption and decryption is different from the back-end, I'm still looking at how to solve it.

**Comment by zurmokeeper** [comment]
@yanghoxom A new version has been released, just upgrade

**Comment by yanghoxom** [comment]
@zurmokeeper
I think logic verify file has password or not is broken for xls
it can not detect file has password. `isEncrypted` return false
`decrypt` do nothing because it also think this file has no password
![image](https://github.com/zurmokeeper/officecrypto-tool/assets/10399540/0dda78ac-69e2-4b04-9988-e8867f43860d)
[test-case-format.xls](https://github.com/user-attachments/files/16023690/test-case-format.xls)

**Comment by zurmokeeper** [comment]
@yanghoxom 

I opened it with WPS and found that you have set up two protections, one that requires a password to open and one that is edit protected (you have to output the password again to edit), so maybe the latter is affecting it, maybe that's the problem here? I'm going to take a hard look at it.

![image](https://github.com/zurmokeeper/officecrypto-tool/assets/25943604/aac2c045-f45b-4c14-9473-628a9a11c016)

![image](https://github.com/zurmokeeper/officecrypto-tool/assets/25943604/1a585b6d-78ed-42db-9f53-c22fcd41a10b)

**Comment by yanghoxom** [comment]
@zurmokeeper Yes, you're right, this is a file with a password, but you need to enter the password twice to open it because when setting the password, the creator selected Excel's `pass modify` option.

**Comment by zurmokeeper** [comment]
@yanghoxom A new version has been released, just upgrade。Temporarily processed, now can be decrypted, but edit mode after decryption disappeared, here still need to study whether the current processing is reasonable?
