### ISSUE TITLE
Decrypting same file produces different output than Python tool

### ISSUE THREAD

**Issue by guillenotfound** [zurmokeeper/officecrypto-tool#33]
This entry is not showing up in the Python document:
<img width="962" alt="image" src="https://github.com/user-attachments/assets/704f848a-94c5-4641-974c-5744ae5ba113">

While the file seems to be working well in MS Office, when I try to use it with https://demo.pdftron.com/demo/ it won't work while Python's one does work. I understand that if the file is vieweable in the official viewer we should assume that the decryption is correct, but since both tools are the same I was expecting both of them to provide the same output file?

This is the original file I'm using (pwd: `Password1234_`):
https://github.com/nolze/msoffcrypto-tool/blob/master/tests/inputs/rc4cryptoapi_password.doc

<img width="481" alt="image" src="https://github.com/user-attachments/assets/9dbfaddf-d940-4979-8984-fa9d57caa74f">

The zip contains the original file (the one I mention above) and the two decrypted files using this tool and [Python](https://github.com/nolze/msoffcrypto-tool/) one:
[files.zip](https://github.com/user-attachments/files/16494798/files.zip)

Additionally this is how it looks in WPS Office:
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/046883cf-3686-449b-a95c-59ee67d3eb05">

**Comment by zurmokeeper** [comment]
I am using The rc4cryptoapi_password_node.doc file you provided is displaying fine in both MS Office and WPS as shown below:
![image](https://github.com/user-attachments/assets/f3f00522-204d-4e1f-a2e7-679b8289a2c3)


I wonder if it's your version of WPS?


node.js decrypted files and python decrypted files, indeed not exactly the same, node.js decrypted out of more than a "\u0001Sh33tJ5" stream. now it seems to be pdftron is not able to recognize this, so it can not be parsed, and WPS and MS Office can be.

I'll see if I can get node.js to return without the "\u0001Sh33tJ5" stream.

**Comment by guillenotfound** [comment]
I've just updated WPS Office from `3.2.0` to `5.7.3` and it seems to be working fine 👍 

Based on that it would be fair to close this issue since I already opened one on PDFTron's end. But before doing that I did yet another test by uploading provided files to Google Drive.

I'm able to open the Python one but not the Node one so there's some differences which are preventing those files to be rendered in other tools, I'd understand if you wouldn't want to invest time on this since the official tools are working just fine and these are in general very old files, if that would be the case please give me a few pointers and I'll try to figure out what other differences are there besides the the extra stream.

Thanks again!

**Comment by zurmokeeper** [comment]
![image](https://github.com/user-attachments/assets/eca0550e-74ad-479e-b1e5-a182c56e4c2b)

@guillenotfound 

The key point is this` "\u0001Sh33tJ5" stream.` node.js decrypted after more than python out of this, should be the problem that led to the failure of the `pdftron `parse, I briefly investigated, it may be `cfb` in the processing of the "\u0001Sh33tJ5" stream of the try to have bugs.` officecrypt-tool` source code is there to delete this stream, but the result is not deleted. If you want to handle it yourself, just delete the `"\u0001Sh33tJ5" stream`.

**Comment by guillenotfound** [comment]
I saw that you have this in place: https://github.com/zurmokeeper/officecrypto-tool/blob/1e0bb680d2a54c1946f9f95083c85d4442ae3633/src/util/doc97.js#L335

But the problem is that when doing write it will add that stream, if you parse output right after doing CFB.write, the stream will be present.

**Comment by zurmokeeper** [comment]
@guillenotfound 

Yes, that's the problem, CFB.write will always add the '\u0001Sh33tJ5' stream, but that should be up to the caller to decide, still trying to figure out how I can get rid of that.

**Comment by guillenotfound** [comment]
Interestingly I've removed that stream manually and tried to open the file again without success. So we can discard this one.

It looks like this change is fixing the issue for both PDFTron and Google Docs, I'm guessing they use `WordDocument` and never fallback to `wordDocument`.

Do you think this could be a valid fix? I don't have enough knowledge on the matter.

<img width="803" alt="image" src="https://github.com/user-attachments/assets/325b2d91-3e20-413b-a286-620dd6a740b9">

**Comment by zurmokeeper** [comment]
@guillenotfound 

Good, that's the problem, I can't believe I misspelled the case w. Feel free to mention PR to fix it!

**Comment by zurmokeeper** [comment]
> Interestingly I've removed that stream manually and tried to open the file again without success. So we can discard this one.
> 
> It looks like this change is fixing the issue for both PDFTron and Google Docs, I'm guessing they use `WordDocument` and never fallback to `wordDocument`.
> 
> Do you think this could be a valid fix? I don't have enough knowledge on the matter.
> 
> <img alt="image" width="803" src="https://private-user-images.githubusercontent.com/5492960/355384682-325b2d91-3e20-413b-a286-620dd6a740b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTIzOTEsIm5iZiI6MTcyMjk1MjA5MSwicGF0aCI6Ii81NDkyOTYwLzM1NTM4NDY4Mi0zMjViMmQ5MS0zZTIwLTQxM2ItYTI4Ni02MjBkZDZhNzQwYjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMTM0ODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmU1M2Y4N2ZlNDk0ZDUzMjFkYjY0YzUxYWU5YWVkODFlZTliMzhiYjk4NGU1NGIwOGZlYWU0NmUyOTRiM2I1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.26Y9tpCjQKKl3zVJaTwbkgRi7o2bgWTOpcXzrmb697k">

By the way, how exactly did you maneuver this manual deletion of the stream? Can I see your code? Or did you use another tool to delete it?

**Comment by guillenotfound** [comment]
> By the way, how exactly did you maneuver this manual deletion of the stream? Can I see your code? Or did you use another tool to delete it?

I used the debugger inside `CFB.write(output)`, the  just `.splice(pos, 1) to remove from both, it was right after `rebuild_cfb(cfb);` which is the one adding that stream IIRC. But from my understanding the that stream should just be ignored.

We are also losing metadata like date because we do recreate the doc, maybe creating a copy and then overriding whichever streams need to be decrypted will do the trick.
