### ISSUE TITLE
Why  the encryption type must be 'standard'?

### ISSUE THREAD

**Issue by DeepSeaFishtot** [zurmokeeper/officecrypto-tool#39]
Hello, I have some doubts in using this tool, I hope you can answer: why, you support ECMA-376 Agile and ECMA-376 Standard encryption algorithms in your code, but you use check in index to stipulate that the encryption type must be 'standard', I want to use your code, but it seems that Microsoft office currently has an agile encryption algorithm, I use Opening a standard encrypted file in Microsoft Excel will prompt that the file is corrupted

**Comment by zurmokeeper** [comment]
@DeepSeaFishtot 

officeCrypto.encrypt(input, {password: '123456'});

options.type is optional, do not pass this parameter, the default export is to use ECMA-376 Agile.

**Comment by DeepSeaFishtot** [comment]
Ok, I see. Thank for your answer
